#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Tue Apr  6 17:03:54 2010

import wx
import Image
import sys

# begin wxGlade: extracode
# end wxGlade





class MyDialog1(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyDialog1.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.bitmap_4 = wx.StaticBitmap(self, -1, wx.Bitmap("/home/matt/code/Citrus/mapmaker/logo.jpg", wx.BITMAP_TYPE_ANY))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyDialog1.__set_properties
        self.SetTitle("Map")
        self.SetSize((314, 303))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyDialog1.__do_layout
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4.Add(self.bitmap_4, 0, wx.ADJUST_MINSIZE, 0)
        self.SetSizer(sizer_4)
        self.Layout()
        # end wxGlade

# end of class MyDialog1


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.notebook_1 = wx.Notebook(self, -1, style=0)
        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, -1)
        
        # Menu Bar
        self.frame_1_menubar = wx.MenuBar()
        self.file = wx.Menu()
        self.new = wx.MenuItem(self.file, wx.NewId(), "&New", "", wx.ITEM_NORMAL)
        self.file.AppendItem(self.new)
        self.open = wx.MenuItem(self.file, wx.NewId(), "&Open", "", wx.ITEM_NORMAL)
        self.file.AppendItem(self.open)
        self.save = wx.MenuItem(self.file, wx.NewId(), "&Save", "", wx.ITEM_NORMAL)
        self.file.AppendItem(self.save)
        self.file.AppendSeparator()
        self.exit = wx.MenuItem(self.file, wx.NewId(), "&Exit", "", wx.ITEM_NORMAL)
        self.file.AppendItem(self.exit)
        self.frame_1_menubar.Append(self.file, "&File")
        wxglade_tmp_menu = wx.Menu()
        self.frame_1_menubar.Append(wxglade_tmp_menu, "&Edit")
        self.SetMenuBar(self.frame_1_menubar)
        # Menu Bar end
        self.button_1 = wx.Button(self.notebook_1_pane_1, -1, "Random")
        self.button_3 = wx.Button(self.notebook_1_pane_1, -1, "button_3")
        self.button_4 = wx.Button(self.notebook_1_pane_1, -1, "button_4")
        self.notebook_1_pane_2 = wx.Panel(self.notebook_1, -1)
        self.notebook_1_pane_3 = wx.Panel(self.notebook_1, -1)
        self.notebook_1_pane_4 = wx.Panel(self.notebook_1, -1)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_MENU, self.onNew, self.new)
        self.Bind(wx.EVT_MENU, self.onOpen, self.open)
        self.Bind(wx.EVT_MENU, self.onSave, self.save)
        self.Bind(wx.EVT_MENU, self.OnExit, self.exit)
        self.Bind(wx.EVT_BUTTON, self.OnBtn1, self.button_1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("Citrus Map Maker")
        self.SetSize((400, 300))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(self.button_1, 0, wx.ADJUST_MINSIZE, 0)
        sizer_3.Add(self.button_3, 0, wx.ADJUST_MINSIZE, 0)
        sizer_3.Add(self.button_4, 0, wx.ADJUST_MINSIZE, 0)
        self.notebook_1_pane_1.SetSizer(sizer_3)
        self.notebook_1.AddPage(self.notebook_1_pane_1, "Height Map")
        self.notebook_1.AddPage(self.notebook_1_pane_2, "Terrain")
        self.notebook_1.AddPage(self.notebook_1_pane_3, "Biome")
        self.notebook_1.AddPage(self.notebook_1_pane_4, "Population")
        sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        self.SetSize((400, 300))
        # end wxGlade

    def OnBtn2(self, event): # wxGlade: MyFrame.<event_handler>
        print "Button 2"
        event.Skip()

    def OnExit(self, event): # wxGlade: MyFrame.<event_handler>
        sys.exit()
        event.Skip()

    def onNew(self, event): # wxGlade: MyFrame.<event_handler>
        print "File->New"
        event.Skip()

    def onOpen(self, event): # wxGlade: MyFrame.<event_handler>
        print "File->Open"
        filename = ""  # Use  filename as a flag
        dlg = wx.FileDialog(self, message="Choose a file")
  
        if dlg.ShowModal() == wx.ID_OK:
            filename = dlg.GetPath()
            dlg.Destroy()
  
        if filename:
            print str(filename)
       event.Skip()

    def onSave(self, event): # wxGlade: MyFrame.<event_handler>
        print "File->Save"
        event.Skip()

    def OnBtn1(self, event): # wxGlade: MyFrame.<event_handler>
        #Button 1: "Random"
        #Create a random static image to build a heightmap from
        #self.dialog_1.bitmap_4 = wx.StaticBitmap(self, -1, wx.Bitmap("/home/matt/Pictures/earth.jpg", wx.BITMAP_TYPE_ANY))

        event.Skip()

# end of class MyFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
